#!/usr/bin/env bash
# gen-sample.sh — Generate a sample project for testing tasklin features.
#
# Creates (or recreates) a `sample/` directory at the repo root containing:
#   - An initialised git repository
#   - Dummy source files to simulate a real project
#   - A .todo/ folder with 1000+ tickets spread across statuses
#
# Usage:
#   bash resources/gen-sample.sh          # run from repo root
#   bash resources/gen-sample.sh --clean  # wipe and regenerate

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SAMPLE_DIR="$REPO_ROOT/sample"

# ---------------------------------------------------------------------------
# Flags
# ---------------------------------------------------------------------------
CLEAN=false
for arg in "$@"; do
  case "$arg" in --clean|-c) CLEAN=true ;; esac
done

if $CLEAN && [ -d "$SAMPLE_DIR" ]; then
  echo "→ Removing existing sample/ directory..."
  rm -rf "$SAMPLE_DIR"
fi

if [ -d "$SAMPLE_DIR/.todo" ]; then
  echo "✓ sample/ already exists. Pass --clean to regenerate."
  exit 0
fi

echo "→ Creating sample project at $SAMPLE_DIR"
mkdir -p "$SAMPLE_DIR"

# ---------------------------------------------------------------------------
# Git repo
# ---------------------------------------------------------------------------
echo "→ Initialising git repository..."
cd "$SAMPLE_DIR"
git init -q
git config user.email "sample@tasklin.dev"
git config user.name "Tasklin Sample"

# ---------------------------------------------------------------------------
# Dummy project files (simulates a small Go service)
# ---------------------------------------------------------------------------
echo "→ Writing dummy project files..."

mkdir -p src/{auth,api,db,worker} tests docs

cat > src/main.go <<'GO'
package main

import "fmt"

func main() {
	fmt.Println("sample service starting...")
}
GO

cat > src/auth/auth.go <<'GO'
package auth

// Token represents an authentication token.
type Token struct {
	Value  string
	UserID int
}

func Validate(t Token) bool {
	return t.Value != "" && t.UserID > 0
}
GO

cat > src/api/router.go <<'GO'
package api

import "net/http"

func NewRouter() *http.ServeMux {
	mux := http.NewServeMux()
	mux.HandleFunc("/health", healthHandler)
	return mux
}

func healthHandler(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
}
GO

cat > src/db/db.go <<'GO'
package db

import "fmt"

type Config struct {
	DSN string
}

func Connect(cfg Config) error {
	if cfg.DSN == "" {
		return fmt.Errorf("DSN is required")
	}
	return nil
}
GO

cat > src/worker/worker.go <<'GO'
package worker

import "time"

type Worker struct {
	interval time.Duration
	stop     chan struct{}
}

func New(interval time.Duration) *Worker {
	return &Worker{interval: interval, stop: make(chan struct{})}
}

func (w *Worker) Start() {
	for {
		select {
		case <-w.stop:
			return
		case <-time.After(w.interval):
			// process jobs
		}
	}
}

func (w *Worker) Stop() { close(w.stop) }
GO

cat > tests/auth_test.go <<'GO'
package tests

import (
	"testing"
)

func TestPlaceholder(t *testing.T) {
	t.Log("placeholder test")
}
GO

cat > docs/architecture.md <<'MD'
# Architecture

This is a sample project used to test tasklin.

## Components

- **auth** — token validation
- **api**  — HTTP routing
- **db**   — database connection
- **worker** — background job processing
MD

cat > README.md <<'MD'
# Sample Project

Auto-generated by `resources/gen-sample.sh` for tasklin development testing.
MD

cat > Makefile <<'MAKE'
.PHONY: build test

build:
	go build ./...

test:
	go test ./...
MAKE

cat > go.mod <<'GOMOD'
module sample

go 1.22
GOMOD

# Commit the dummy files so git has a history to work with
git add .
git commit -q -m "chore: initial sample project scaffold"

# Create a feature branch to test branch-aware features
git checkout -q -b feature/sample-work

# ---------------------------------------------------------------------------
# .todo directory and config
# ---------------------------------------------------------------------------
echo "→ Writing .todo/config.yaml..."
mkdir -p .todo

cat > .todo/config.yaml <<'YAML'
title_limit: 80
default_done_status: Done
auto_commit_on_done: false
statuses:
  - id: 1
    name: To Do
    color: red
    order: 0
  - id: 2
    name: In Progress
    color: yellow
    order: 1
  - id: 3
    name: Review
    color: blue
    order: 2
  - id: 4
    name: Done
    color: green
    order: 3
YAML

# ---------------------------------------------------------------------------
# tickets.yaml — 1 000 tickets across four statuses
# ---------------------------------------------------------------------------
echo "→ Generating 1 000 tickets..."

STATUSES=("To Do" "In Progress" "Review" "Done")

# Weight distribution: To Do 40%, In Progress 20%, Review 15%, Done 25%
weights=(40 20 15 25)

# Adjective + noun pools for realistic-looking titles
ADJECTIVES=(
  "Add" "Fix" "Refactor" "Update" "Remove" "Implement" "Optimise" "Document"
  "Test" "Review" "Migrate" "Integrate" "Extend" "Validate" "Clean up"
  "Deprecate" "Expose" "Harden" "Monitor" "Profile" "Resolve" "Simplify"
  "Upgrade" "Wire up" "Extract"
)

NOUNS=(
  "authentication flow" "login endpoint" "password reset" "token refresh"
  "user profile page" "avatar upload" "email verification" "OAuth integration"
  "database migrations" "connection pooling" "query optimisation" "index strategy"
  "background worker" "job queue" "retry logic" "dead-letter handling"
  "REST API versioning" "GraphQL schema" "webhook delivery" "rate limiting"
  "CI pipeline" "test coverage" "integration tests" "load tests"
  "Docker image" "Kubernetes manifests" "Helm chart" "deployment script"
  "logging middleware" "error tracking" "alerting rules" "dashboard metrics"
  "admin panel" "user permissions" "role management" "audit log"
  "file storage" "CDN integration" "cache layer" "search indexing"
  "payment gateway" "subscription billing" "invoice generation" "tax handling"
  "mobile API" "push notifications" "deep linking" "app versioning"
  "dark mode support" "accessibility audit" "i18n strings" "RTL layout"
  "code review process" "PR template" "changelog automation" "release notes"
  "dependency audit" "licence compliance" "security headers" "CORS policy"
  "feature flags" "A/B testing" "analytics events" "conversion funnel"
  "onboarding flow" "help centre" "feedback widget" "NPS survey"
  "data export" "CSV import" "bulk operations" "pagination cursor"
  "websocket support" "SSE endpoint" "long polling fallback" "connection keepalive"
  "schema validation" "input sanitisation" "output encoding" "CSRF protection"
)

# Label pool — valid identifiers, used for autocomplete and ticket assignment
LABELS=(
  "api" "backend" "bug" "chore" "core"
  "database" "docs" "enhancement" "feature" "frontend"
  "infra" "milestone" "mobile" "performance" "security"
  "testing" "ux" "urgent" "v1" "v2"
)
LABEL_COUNT=${#LABELS[@]}

# Build a weighted status array
STATUS_POOL=()
for i in "${!STATUSES[@]}"; do
  for (( w=0; w<${weights[$i]}; w++ )); do
    STATUS_POOL+=("${STATUSES[$i]}")
  done
done
POOL_SIZE=${#STATUS_POOL[@]}

# Emit tickets.yaml
{
  echo "tickets:"
  now=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  for (( id=1; id<=1000; id++ )); do
    adj="${ADJECTIVES[$(( (id * 7 + 3) % ${#ADJECTIVES[@]} ))]}"
    noun="${NOUNS[$(( (id * 13 + 5) % ${#NOUNS[@]} ))]}"
    title="${adj} ${noun}"
    status="${STATUS_POOL[$(( (id * 31 + 11) % POOL_SIZE ))]}"

    # Stagger created_at dates over the past year
    days_ago=$(( id % 365 ))
    created=$(date -u -v-"${days_ago}d" +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null \
      || date -u -d "${days_ago} days ago" +"%Y-%m-%dT%H:%M:%SZ")

    echo "  - id: ${id}"
    echo "    title: \"${title}\""
    echo "    status: \"${status}\""

    # Assign 0–2 labels deterministically (≈30% none, 40% one, 30% two)
    lc=$(( (id * 17 + 3) % 10 ))
    if   (( lc <= 2 )); then lc=0
    elif (( lc <= 6 )); then lc=1
    else                     lc=2
    fi
    if (( lc >= 1 )); then
      li1=$(( (id * 11 + 7) % LABEL_COUNT ))
      lbl1="${LABELS[$li1]}"
    fi
    if (( lc == 2 )); then
      li2=$(( (li1 + 1 + id % (LABEL_COUNT - 1)) % LABEL_COUNT ))
      lbl2="${LABELS[$li2]}"
    fi
    if (( lc == 1 )); then
      echo "    labels:"
      echo "      - ${lbl1}"
    elif (( lc == 2 )); then
      echo "    labels:"
      echo "      - ${lbl1}"
      echo "      - ${lbl2}"
    fi

    echo "    created_at: ${created}"

    # Add a transition for anything not in To Do
    if [ "$status" != "To Do" ]; then
      echo "    transitions:"
      echo "      - from: To Do"
      echo "        to: \"${status}\""
      echo "        at: ${created}"
    fi
  done
} > .todo/tickets.yaml

# Write the autocomplete index — all labels from the pool, sorted
echo "→ Writing .todo/labels.yaml..."
{
  echo "labels:"
  for lbl in "${LABELS[@]}"; do
    echo "  - ${lbl}"
  done
} > .todo/labels.yaml

echo "→ Committing .todo data to the feature branch..."
git add .todo/
git commit -q -m "chore: add sample tasklin data (1000 tickets, labels)"

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
echo "✓ Sample project ready at: $SAMPLE_DIR"
echo ""
echo "  Run tasklin from inside it:"
echo "    cd $SAMPLE_DIR"
echo "    tasklin"
echo ""
echo "  Or point tasklin at it directly (if supported)."
echo ""
