# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tasklin < Formula
  desc "Keyboard-driven CLI/TUI kanban board for personal project backlogs"
  homepage "https://github.com/yamidaisuke/tasklin"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yamidaisuke/tasklin/releases/download/v2.0.0/tasklin_darwin_amd64.tar.gz"
      sha256 "80162cbb96b00892e49cf1a2ba373680ed8e6e74d38e08ac25978510893f41f0"

      define_method(:install) do
        bin.install "tasklin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yamidaisuke/tasklin/releases/download/v2.0.0/tasklin_darwin_arm64.tar.gz"
      sha256 "b8c668e4238d44fe589ab9ce04f16e5aefecdb5be63413f5e7fc675f253a258b"

      define_method(:install) do
        bin.install "tasklin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yamidaisuke/tasklin/releases/download/v2.0.0/tasklin_linux_amd64.tar.gz"
      sha256 "fd07a4e6e4903bba045670c4b48dbd74a1e865b6a364d59fef7cbe9a5008d180"
      define_method(:install) do
        bin.install "tasklin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yamidaisuke/tasklin/releases/download/v2.0.0/tasklin_linux_arm64.tar.gz"
      sha256 "3aa7dfff54580c187de361f450befa6a09b6bc53fc9cbbe0a3b5bfbd6d9b91f1"
      define_method(:install) do
        bin.install "tasklin"
      end
    end
  end

  test do
    system "#{bin}/tasklin", "--version"
  end
end
